# Generated by Django 3.2 on 2021-06-02 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_auto_20210602_0909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderedproduct',
            options={'verbose_name': 'Заказанный товар', 'verbose_name_plural': 'Заказанные товары'},
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.product', verbose_name='Товар в заказе'),
        ),
    ]
